name: Dev Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.13.0

      - name: Use the latest bedrock-skin
        shell: bash
        working-directory: frontend
        run: |
          npm install bedrock-skin@latest
          npm ls bedrock-skin

      - name: Build
        shell: bash
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          wails build -upx -ldflags "-s -w -X main.currentVersion=dev-${SHORT_SHA}"
